
// This file has been generated by the GUI designer. Do not modify.
namespace DenTal_Payment_Form.Properties
{
	public partial class Window
	{
		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget DenTal_Payment_Form.Properties.Window
			this.Name = "DenTal_Payment_Form.Properties.Window";
			this.Title = global::Mono.Unix.Catalog.GetString("Window");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
